name: platform_image_converter_example
description: "Demonstrates how to use the platform_image_converter plugin."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter

  platform_image_converter:
    path: ../
  image_picker: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
