name: image_ffi
description: "A high-performance Flutter plugin for cross-platform image format conversion using native APIs."
version: 0.0.1
homepage: https://github.com/koji-1009/image_ffi

environment:
  sdk: ^3.10.0
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter
  jni: ^0.15.2
  ffi: ^2.1.4
  objective_c: ^9.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  jnigen: ^0.15.0
  ffigen: ^20.1.1
